### ISSUE TITLE
Downloads get interrupted around 98% completion

### ISSUE THREAD

**Issue by zda** [CollectionFS/Meteor-cfs-s3#34]
(Moved from https://github.com/CollectionFS/Meteor-CollectionFS/issues/466 on the main package)

Many images I upload using CollectionFS cannot be fully downloaded reliably (it is nondeterministic); the downloads typically are interrupted at 95-99% completion, and then stop. This seems to only affect cfs:s3 uploads.

Typical examples below. Red shows portion of image not downloaded. It only happens on remote servers, not in development, which perhaps provides a clue:

![screen shot 2014-11-04 at 3 29 27 pm](https://cloud.githubusercontent.com/assets/4313606/4910055/893b4194-647a-11e4-8088-771d9a7b4c97.png)
(localhost:3000)

![screen shot 2014-11-04 at 3 27 49 pm](https://cloud.githubusercontent.com/assets/4313606/4910060/94f3445a-647a-11e4-891b-87e1b2124622.png)
(http://collectionfs-download-issue.meteor.com)

This happens on Meteor.com, Modulus, and Heroku, so I don't think it is a PaaS-specific issue. I'm using `cfs:s3` and `cfs:gridfs` (same issue with `cfs:filesystem`).

In case it helps: the server logs on Heroku say the GET was interrupted on the server side ([Heroku error H18](https://devcenter.heroku.com/articles/error-codes#h18-request-interrupted), sock=backend).

Repo that reproduces the issue: https://github.com/zda/collectionfs-download-issue

Deployed at: http://collectionfs-download-issue.meteor.com/

Be sure to use incognito tabs in Chrome if you load the above page multiple times to get around browser caching.

You can deploy the above app yourself with `meteor deploy <name> --settings settings.json`, where `settings.json` is a file in app root like this:

```
{
  "AWS_ACCESS_ID":"<id>",
  "AWS_SECRET_ACCESS_KEY":"<key>"
  "BUCKET_NAME":"<name>"
}
```

Not publishing my AWS credentials for obvious reasons :) I'm testing different buckets now, even though there seems to be nothing unusual about the one I've been using. Seems like a package issue though since S3/my bucket works fine in a development environment.

**Comment by tom2strobl** [comment]
I think I'm still experiencing this. When I upload a 3-minute audio file and observe the collection cursor the isUploaded is fired too early and the uploaded file on S3 only lasts for 2 minutes+Xseconds (the filesize is also smaller). This also leads to "Error: Error storing file to the media store: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed." in the server console
See: https://gist.github.com/tom2strobl/66bb1e5e44d88ce2e8ca

**Comment by tom2strobl** [comment]
Here's the FS.debug log

  <Buffer 2d 2d 2d 2d 2d 2d 57 65 62 4b 69 74 46 6f 72 6d 42 6f 75 6e 64 61 72 79 4c 78 53 50 6d 4d 49 56 57 69 67 36 70 78 62 72 0d 0a 43 6f 6e 74 65 6e 74 2d 44 ...>
  13238070
  fileObj.createReadStream creating read stream for attached data
  createWriteStream _tempstore, internal: true
  createWriteStreamForFileKey _tempstore
  -----------FINISH STREAM _tempstore
  SA FileSystem - DONE!! fileKey: "media-GKwsesd9WcDCtA2BY-0.chunk"
  -----------STORED STREAM _tempstore
  -----------CLOSE STREAM _tempstore
  TempStore progress: Received 1 of 1 chunks for test.mp3
  UPDATE: {"$set":{"uploadedAt":"2015-02-10T14:50:05.580Z"},"$unset":{"chunkCount":1,"chunkSum":1,"chunkSize":1}}
  test.mp3 was successfully uploaded. You are seeing this informational message because you enabled debugging and you have not defined any listeners for the "uploaded" event on the media collection.
  GET FILERECORD: GKwsesd9WcDCtA2BY
  FileWorker ADDED - calling saveCopy media for GKwsesd9WcDCtA2BY
  saving to store media
  createWriteStream media, internal: false
  createWriteStreamForFileKey media
  FS.TempStore creating read stream for GKwsesd9WcDCtA2BY
  createReadStream _tempstore
  createReadStreamForFileKey _tempstore
  Received POST message and saved successfully
  -----------FINISH STREAM media
  -----------FINISH STREAM media
  SA S3 - DONE!!
  -----------STORED STREAM media
  -----------STORED STREAM media
  SA media stored media/GKwsesd9WcDCtA2BY-test.mp3
  FS.File._saveChanges: media
  UPDATE: {"$set":{"copies.media":{"name":"test.mp3","type":"audio/mp3","size":10616832,"key":"media/GKwsesd9WcDCtA2BY-test.mp3","updatedAt":"2015-02-10T14:50:23.268Z","createdAt":"2015-02-10T14:50:23.268Z"}}}
  test.mp3 was successfully saved to the media store. You are seeing this informational message because you enabled debugging and you have not defined any listeners for the "stored" event on the media collection.
  FileWorker ADDED - calling deleteChunks for GKwsesd9WcDCtA2BY
  ---SA REMOVE
  SA S3 - ERROR!!
  -----------ERROR STREAM media The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
  -----------ERROR STREAM media The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.

the problem is that on the update of copies.media the size information equals to the size of the document on S3, which is ~10.13 MB, the real filesize is 13.2 MB though.
Also I'm wondering why it says chunkCount: 1 on a 13.2 MB file, shouldn't it be 2-3 chunks? I didn't override the default chunk size.

**Comment by aldeed** [comment]
Released the fix for large file sizes. Please post whether that fix seems to fix this issue, too.

**Comment by tom2strobl** [comment]
Jeez that was fast. Working like a charm, you guys rock so bad! Keep it up.
