### ISSUE TITLE
Question: storing in a different folder on a per-user basis

### ISSUE THREAD

**Issue by tanis2000** [CollectionFS/Meteor-cfs-s3#49]
Hi guys,

is it possible to set the folder of the uploaded file on a per-file basis instead of setting it in the storage object?
The use-case is to be able to store the files of a certain user inside that user's own folder instead of storing all of the files in a shared one.
Thanks!

**Comment by aldeed** [comment]
You can add `fileKeyMaker` option on your store, and set it to a function that returns the file key given a fileObj (FS.File instance). For now, you actually need to add some code to your function checking to see if a file key is already assigned. Hopefully we can handle that internally eventually.

Here's an example that would generate the same fileKey as default:

```js
var imageStore = new FS.Store.FileSystem("images", {
  fileKeyMaker: function (fileObj) {
    // Lookup the copy
    var store = fileObj && fileObj._getInfo(name);
    // If the store and key is found return the key
    if (store && store.key) return store.key;

    // TO CUSTOMIZE, REPLACE CODE AFTER THIS POINT

    var filename = fileObj.name();
    var filenameInStore = fileObj.name({store: name});

    // If no store key found we resolve / generate a key
    return fileObj.collectionName + '/' + fileObj._id + '-' + (filenameInStore || filename);
  }
});
```

The function receives only the `fileObj` so you'll need to set the current userId on every file when uploading in order to use it in your path.

S3 automatically creates the necessary folders based on the slashes in the string you return.

**Comment by tanis2000** [comment]
@aldeed thanks for the bit of code, that really enlightened me on how to work with this. I was also wondering if the fileObj._id is actually guaranteed to be unique or it could by any chance be duplicated. Any idea?

**Comment by aldeed** [comment]
At this point the metedata doc has already been inserted, so _id will definitely be unique due to unique index on _ids in mongo that would have prevented insertion otherwise.

**Comment by tanis2000** [comment]
@aldeed I forgot to report back that this worked a charm! You guys rock!
